import { Link } from "react-router-dom";

export default function PrivacyPage() {
  const updated = "1 June 2025";

  return (
    <div className="min-h-screen bg-surface">
      <div className="max-w-3xl mx-auto px-6 py-12 space-y-10">
        <div className="space-y-2">
          <Link to="/" className="text-xs text-text-dim hover:text-accent transition-colors">
            ← Back to QueryPrism
          </Link>
          <h1 className="text-2xl font-bold text-text mt-3">Privacy Policy</h1>
          <p className="text-xs text-text-dim">Last updated: {updated}</p>
        </div>

        <Section title="1. Introduction">
          <p>
            QueryPrism ("we", "our", or "us") operates a B2B SaaS platform that enables organisations
            to build AI-powered knowledge bases and query them through a retrieval-augmented generation
            (RAG) pipeline. This Privacy Policy describes how we collect, use, store, and protect the
            personal data of users and administrators who access our service at queryprism.com
            (the "Service").
          </p>
          <p>
            By creating an account or using the Service you agree to this policy. If you are
            accessing the Service on behalf of your employer, you represent that you have the
            authority to bind that organisation to these terms.
          </p>
        </Section>

        <Section title="2. Data We Collect">
          <Subsection title="2.1 Account information">
            When you register we collect your name, email address, organisation name, and a
            hashed password. Administrators may additionally provide billing contact details and
            company tax identifiers.
          </Subsection>
          <Subsection title="2.2 Documents and knowledge base content">
            You upload files (PDF, DOCX, TXT, and other supported formats) to populate your
            knowledge base. These documents are stored securely in encrypted object storage and
            processed to extract text chunks and vector embeddings. We do not read or use your
            documents for any purpose other than powering your own queries.
          </Subsection>
          <Subsection title="2.3 Query data">
            When a user submits a question we record the query text, the retrieved source
            chunks used to construct the answer, the AI-generated response, and metadata
            (timestamp, user ID, team ID). This data is used to compute usage metrics and to
            serve cached responses for identical queries within the same billing period.
          </Subsection>
          <Subsection title="2.4 Usage and billing metrics">
            We track the number of queries executed, total storage consumed, number of teams and
            users provisioned, and the current subscription plan in order to enforce plan limits
            and generate invoices.
          </Subsection>
          <Subsection title="2.5 Audit log">
            Administrative actions — such as inviting users, changing roles, or modifying company
            settings — are recorded in an immutable audit log tied to the acting user's identity.
          </Subsection>
          <Subsection title="2.6 Technical data">
            We collect IP addresses, browser user-agent strings, and request logs for security
            monitoring, abuse prevention, and debugging purposes.
          </Subsection>
        </Section>

        <Section title="3. How We Use Your Data">
          <ul className="list-disc pl-5 space-y-1.5">
            <li>To provision and operate your account and knowledge base.</li>
            <li>To answer queries by passing retrieved context to our AI model provider.</li>
            <li>To enforce subscription plan limits and generate billing invoices.</li>
            <li>To send transactional emails (invitations, password resets, billing notifications).</li>
            <li>To maintain security, detect fraud, and comply with legal obligations.</li>
            <li>To improve the reliability and performance of the Service (aggregated, anonymised telemetry only).</li>
          </ul>
          <p className="mt-3">
            We do not sell your personal data or use it to train AI models. We do not display
            advertising.
          </p>
        </Section>

        <Section title="4. AI Model Provider">
          <p>
            Query responses are generated by large language models provided by Anthropic, PBC
            ("Anthropic") via the Claude API. When you submit a query, the retrieved document
            chunks and your question are transmitted to Anthropic's API over an encrypted
            connection. Anthropic's data processing terms apply to this transmission and Anthropic
            does not use customer API inputs to train its models.
          </p>
          <p>
            We select the model tier (Haiku, Sonnet, or Opus) based on your subscription plan.
            You can find the applicable model for your plan on the Billing page.
          </p>
        </Section>

        <Section title="5. Data Storage and Security">
          <p>
            All data is stored within the European Union. We apply the following controls:
          </p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Encryption at rest (AES-256) for all database volumes and object storage.</li>
            <li>TLS 1.2+ in transit for all network communication.</li>
            <li>Role-based access control — users can only query knowledge bases belonging to
              their own teams; cross-tenant data access is prevented at the database layer.</li>
            <li>JWT-based authentication with short-lived tokens.</li>
            <li>Regular automated backups with point-in-time recovery.</li>
          </ul>
        </Section>

        <Section title="6. Data Retention">
          <p>
            Account data and knowledge base content are retained for the lifetime of your
            subscription plus a 30-day grace period following cancellation, after which all
            data is permanently deleted.
          </p>
          <p>
            Audit logs are retained for 12 months. Query history is retained for 90 days.
            Technical request logs are retained for 30 days.
          </p>
        </Section>

        <Section title="7. Your Rights">
          <p>
            If you are located in the European Economic Area, the United Kingdom, or another
            jurisdiction with applicable data protection law, you have the right to:
          </p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li><strong>Access</strong> — request a copy of the personal data we hold about you.</li>
            <li><strong>Rectification</strong> — correct inaccurate data via your User Settings page.</li>
            <li><strong>Erasure</strong> — request deletion of your account and associated data.</li>
            <li><strong>Portability</strong> — receive your data in a structured, machine-readable format.</li>
            <li><strong>Restriction / Objection</strong> — restrict or object to certain processing activities.</li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, email us at <strong>privacy@queryprism.com</strong>.
            We will respond within 30 days.
          </p>
        </Section>

        <Section title="8. Cookies">
          <p>
            The Service uses only strictly necessary session cookies to maintain your authenticated
            session. We do not use tracking, analytics, or advertising cookies.
          </p>
        </Section>

        <Section title="9. Third-Party Sub-processors">
          <p>We use the following sub-processors to deliver the Service:</p>
          <table className="w-full text-xs border border-border rounded mt-2">
            <thead>
              <tr className="bg-panel text-text-dim">
                <th className="text-left px-3 py-2 border-b border-border">Sub-processor</th>
                <th className="text-left px-3 py-2 border-b border-border">Purpose</th>
                <th className="text-left px-3 py-2 border-b border-border">Location</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Anthropic, PBC", "LLM inference (Claude API)", "USA"],
                ["Cloud infrastructure provider", "Compute, storage, networking", "EU"],
                ["Postfix / SMTP relay", "Transactional email delivery", "EU"],
              ].map(([name, purpose, loc]) => (
                <tr key={name} className="border-b border-border last:border-0">
                  <td className="px-3 py-2 text-text">{name}</td>
                  <td className="px-3 py-2 text-text-dim">{purpose}</td>
                  <td className="px-3 py-2 text-text-dim">{loc}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Section>

        <Section title="10. Changes to This Policy">
          <p>
            We may update this policy from time to time. We will notify account owners by email
            at least 14 days before material changes take effect. Continued use of the Service
            after the effective date constitutes acceptance of the revised policy.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            For privacy-related enquiries, contact our Data Protection Officer at{" "}
            <strong>privacy@queryprism.com</strong>.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-semibold text-text border-b border-border pb-1">{title}</h2>
      <div className="text-sm text-text-dim space-y-3 leading-relaxed">{children}</div>
    </section>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1">
      <h3 className="text-xs font-semibold text-text">{title}</h3>
      <p>{children}</p>
    </div>
  );
}
